import type { Metadata } from "next";
import "./globals.css";
import 'react-responsive-pagination/themes/classic.css';
import localFont from 'next/font/local'
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const varelaFont = localFont({
  src: "../public/fonts/varela.ttf",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${varelaFont.className} w-full min-h-screen flex flex-col items-center justify-start`}>
        <Header />
        <main className="w-full h-full flex-1 flex flex-col items-center justify-start border-y-[0.5px] border-solid border-gray-500">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
