name: Deploy to Server

on:
  push:
    branches:
      - master  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ 
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEApvswgxlyb9dSQWIiHyITFwStV93ZQxYaF5HE2d47Cl+Y4dhQLjyE
2xlqhR/u6atHPjb8fMNx6GsiS3oMr/CUWiNcYQdwGT9D8Y4kp14ypRCoibE0Mpawu+BLQU
p6q5aDaxp/KFnXDz+OolfVXb+elhKwZMB8MZyg9PVZ2GA5IKr5Ymzp/EbaPZOt0NFVn4v8
4Yv+7PfOI8NSyZMwu1lqYmcGw2/8JuTu5hpt8u78e7UjpcCq5KjiAJ7l1DLRDQCgPE4v+Q
2+DShtd2zpKIvE2wZjq2ant+KGUnfZVVhYIyssZ2/D2pIobrAQt0BRfuiY9C6tSRlEvXwA
iFDsSe1bMv/mgCVxYE1tmPdrdVGbbaEL6I8maDglRUbYXkaOl50m3yO9hIr+oNW3vX7I/w
X9ni5T+9KWfnWYyXiFWsu2wAEEM+04r+vfdGyfzP832EwTcDMitgEzvfQX1o3rZ0GzIaAz
97yz1XSdkaJIK6cq0OhHC0oEG3psTiXD35g2XJ1WXi2GL7jc8YlhgbAH1kgNQ9ZE7zlYJ+
9UMCHHdaAqzyHUkP5YbB18LP5vINpIzIbHRPF9mJ6W/BfRWsiIWhVZAQiF2k9sBuLA2XQ2
/Bgds1zzAMHvQsDDk1OcmVtt/rxq5tfgkNevYOyoxgb6gYRXhSwiEMbKdzJdhp+v+9RsCn
cAAAdQLVhgfS1YYH0AAAAHc3NoLXJzYQAAAgEApvswgxlyb9dSQWIiHyITFwStV93ZQxYa
F5HE2d47Cl+Y4dhQLjyE2xlqhR/u6atHPjb8fMNx6GsiS3oMr/CUWiNcYQdwGT9D8Y4kp1
4ypRCoibE0Mpawu+BLQUp6q5aDaxp/KFnXDz+OolfVXb+elhKwZMB8MZyg9PVZ2GA5IKr5
Ymzp/EbaPZOt0NFVn4v84Yv+7PfOI8NSyZMwu1lqYmcGw2/8JuTu5hpt8u78e7UjpcCq5K
jiAJ7l1DLRDQCgPE4v+Q2+DShtd2zpKIvE2wZjq2ant+KGUnfZVVhYIyssZ2/D2pIobrAQ
t0BRfuiY9C6tSRlEvXwAiFDsSe1bMv/mgCVxYE1tmPdrdVGbbaEL6I8maDglRUbYXkaOl5
0m3yO9hIr+oNW3vX7I/wX9ni5T+9KWfnWYyXiFWsu2wAEEM+04r+vfdGyfzP832EwTcDMi
tgEzvfQX1o3rZ0GzIaAz97yz1XSdkaJIK6cq0OhHC0oEG3psTiXD35g2XJ1WXi2GL7jc8Y
lhgbAH1kgNQ9ZE7zlYJ+9UMCHHdaAqzyHUkP5YbB18LP5vINpIzIbHRPF9mJ6W/BfRWsiI
WhVZAQiF2k9sBuLA2XQ2/Bgds1zzAMHvQsDDk1OcmVtt/rxq5tfgkNevYOyoxgb6gYRXhS
wiEMbKdzJdhp+v+9RsCncAAAADAQABAAACADa81hDLyTc/ev/i9vOEvIRJrLdGir+SobgD
OWgAEROb9eZm/hXCEf0uzjvYlX10/7Q12zvc59y8LfBXEIymTUNlHxXRld443oFzSrGwz+
JLXSxR8h35RvM3mgPLsf3Ip8j21SM5nCWr/IpcR53lQEvK0ZcdgDjVMvBJ84taM6/xTDIH
KQbhhQ41eH+g97QG9D1NoqI0s5cGov9gKFPqAlVCl7V+YsavOl8k39EIpay52vctevfdIs
T4Ubfndp8QCvbp3JEEf74ZeBTzl1UKyFvSMt8PlkBR2h1zm0N+Y9oXf4Vi3m2qhuWOAtTH
mU+EWQuGt5hkV6PT3+rPuD2duMyuAAzD5bS8jY3H2DmLNpOKqcD/0DM/MHGGHQY6QkBfDi
6aBkTKTcg5gVBE2UcSipt2NytZSIl7ozgLzJPsXvld1SHp5OXjPDGofypALgdGvb5Ych89
EVr+JfWRWX9FJceyCVTeeoQJdcqgNEmdPvHKFRWZKcjVYE2YaB002s3XMZ5zMq8Iejtwdl
og1JvYyrb2JiwFCKSuFdiSaHJd7tezATJICXAEa+LKpUuG41+OS5lV6hAJYdX3Gqxgvihy
0rylkxbRRYyPlfMDZFHcHOkHj1XIXSwr5wTATLIHvU5GjCgrxqww02IWCCbRWmkMHgF2Gj
ie9A8ALDiRSZ92icNhAAABAB/Lbv1smmGwC8lnlVpJvFT62m/UlzRIG6E7l99DKXYpqY1z
AIGOQqYFETlisFvqRqAsGtxnKJ3GEKJmBtF8dt2q/1gzuNBxup+KEKQTVu+YQ3/9T/9Ogd
vZ9JI0oubQtbocFYBHT6Ex7L+6is6XGIlwUYehVdD6jx2GzNWzuyCQVnfz1WAxz++v/yRC
kzlVhkva/xfdL3e1nzAB5bS1C/2fGZWDrBrSxY9ZY4no4oPd3o8Ex9G2/qjdt15OuGdQr2
EEwCpfc9Spr4Z2i7L961mNSwhLfZgfa+x1pkP9mDo/wt3dTnWk81tMSt83rVnAFE6GjNir
rBTsg5INqes1g1IAAAEBANMz109g7xBTGZKeIwcZW3jM5DiQD+e2wE80Ml9o8b/HS1lPYM
6m1HSHXC1O3OhPKD73yX3j2kEK5P/cWPkMGVNNNaY0ZgObvZUT7s5e0x8RHA2uNuZ3Dd8t
Z+o/8ApAVh5Bx8/FYOa2PpDEzhYP598d6OS0Ko0iko3e+qix2lxVr+53RV312CYq6XsCQk
8KN8giKf8B/NiD1WD1tmj3dBOeJRu66NmX+wetfSVEdbVxeiV5oUYti/t8UqhA84e3bvd/
z/aN/YHq0aGxexKn0SRWSymgADjFlrOhUEg0spztzfKExN+PFJGkWc5A794mx5aNlAit4B
vkny5kqmjgYFcAAAEBAMpmKSrgqDdyIwDZe7HA/zaz7hcMU2ZtNkjWUQGf+7RvVBvIe99Y
gEYe/cNaWpm7bOYTb520C1ro7GnIC8R81jPOlAt8bfzaxrM3WZJ6qbXdkofpk38inhsvJ+
VF8eKonbE6mL3yk/1EjJr/Fjf4yb5k/KR8qxcu+DI8NVP+hYfncMqF4JaBBtNshRdrWHV1
CiZ3iinFcEJtNFzFds8KDwzkIZjq3BJgBmRoU3rIt60H45OL1BSLjLXHxbTldzZTUVipFw
oadZZDCb4kFjGwndW6UqKZhtVilLTjmSVwh0U6Upm9oOYAOJsHISZjoxOAlu1XEB5/wbcH
B99HGktQ0uEAAAAZYXJhc2hhbHRhZmkxMzc3QGdtYWlsLmNvbQEC
        }}

    - name: Deploy to server
      run: |
        ssh your-server-user@your-server-ip << 'EOF'
          cd /var/www/crypto-next
          git pull origin master
          npm install
          npm run build
          pm2 restart crypto
        EOF
