name: Deploy to Server

on:
  push:
    branches:
      - master  # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCm+zCDGXJv11JBYiIfIhMXBK1X3dlDFhoXkcTZ3jsKX5jh2FAuPITbGWqFH+7pq0c+Nvx8w3HoayJLegyv8JRaI1xhB3AZP0PxjiSnXjKlEKiJsTQylrC74EtBSnqrloNrGn8oWdcPP46iV9Vdv56WErBkwHwxnKD09VnYYDkgqvlibOn8Rto9k63Q0VWfi/zhi/7s984jw1LJkzC7WWpiZwbDb/wm5O7mGm3y7vx7tSOlwKrkqOIAnuXUMtENAKA8Ti/5Db4NKG13bOkoi8TbBmOrZqe34oZSd9lVWFgjKyxnb8PakihusBC3QFF+6Jj0Lq1JGUS9fACIUOxJ7Vsy/+aAJXFgTW2Y92t1UZttoQvojyZoOCVFRtheRo6XnSbfI72Eiv6g1be9fsj/Bf2eLlP70pZ+dZjJeIVay7bAAQQz7Tiv6990bJ/M/zfYTBNwMyK2ATO99BfWjetnQbMhoDP3vLPVdJ2RokgrpyrQ6EcLSgQbemxOJcPfmDZcnVZeLYYvuNzxiWGBsAfWSA1D1kTvOVgn71QwIcd1oCrPIdSQ/lhsHXws/m8g2kjMhsdE8X2Ynpb8F9FayIhaFVkBCIXaT2wG4sDZdDb8GB2zXPMAwe9CwMOTU5yZW23+vGrm1+CQ169g7KjGBvqBhFeFLCIQxsp3Ml2Gn6/71GwKdw== arashaltafi1377@gmail.com }}

    - name: Deploy to server
      run: |
        ssh your-server-user@your-server-ip << 'EOF'
          cd /var/www/crypto-next
          git pull origin master
          npm install
          npm run build
          pm2 restart crypto
        EOF
